name = "Miakube"
author = "Miaourt"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0afc81ac341110abeec8be4ae920aaff0a83fb478c23f857aab2ff20cee5cc45"

[versions]
forge = "40.1.80"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18", "1.18.0", "1.18.1", "1.18.2"]
